# Generated by Django 6.0.2 on 2026-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'Mechanical'), ('civil', 'Civil'), ('cse-ds', 'CSE-Data Science'), ('cse-aiml', 'CSE-AIML'), ('cse-aids', 'CSE-AIDS'), ('cse-ai', 'CSE-AI')], default='cse-ds', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=8),
        ),
    ]
